spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/training
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml